import './assets/styles/style.scss'

import './assets/js/shared.js'

import './assets/images/logo.svg'
import './assets/images/usp-arrow.svg'
import './assets/images/usp-icon-people.svg'
import './assets/images/usp-icon-coffee.svg'
import './assets/images/usp-icon-circle.svg'
import './assets/images/usp-icon-architecture.svg'
import './assets/images/border-polygon.svg'
import './assets/images/button-fullscreen.svg'
import './assets/images/drawing.png'

import './assets/images/Being.png'
import './assets/images/Delva.png'
import './assets/images/Powerhouse.png'
import './assets/images/REDC.png'
import './assets/images/TUe.png'
import './assets/images/vbt.png'

import './assets/images/back-arrow.svg'
import './assets/images/plan.png'
import './assets/images/aanzichten.png'
import './assets/images/windrichting.svg'
import './assets/images/open360.svg'
import './assets/images/logo-b.svg'
import './assets/images/kaart.png'
