import './assets/styles/style.scss'

import './assets/js/shared.js'

import './assets/images/logo.svg'
import './assets/images/usp-arrow.svg'
import './assets/images/usp-icon-green.svg'
import './assets/images/usp-icon-community.svg'
import './assets/images/usp-icon-sustainability.svg'
import './assets/images/usp-icon-location.svg'
import './assets/images/border-polygon.svg'
import './assets/images/button-fullscreen.svg'
import './assets/images/drawing.png'

import './assets/images/Being.png'
import './assets/images/Delva.png'
import './assets/images/Powerhouse.png'
import './assets/images/REDC.png'
import './assets/images/TUe.png'
import './assets/images/vbt.png'

import './assets/images/back-arrow.svg'
import './assets/images/plan.png'
import './assets/images/aanzichten.png'
import './assets/images/windrichting.svg'
